n1 = input('Informe o primeiro numero: ')

print('O tipo primitivo desse valor é: ', type(n1))
print('É só espaços?', n1.isspace())
print('É numerico? ', n1.isnumeric())
print('É alfabetico? ', n1.isalpha())
print('É alfanumerico?', n1.isalnum())
print('Possui somente letras maisculas? ', n1.isupper())
print('Possui somente letras maisculas? ', n1.islower())
print('Possui somente letras maisculas? ', n1.istitle())